### ISSUE TITLE
"que une"

### ISSUE THREAD

**Issue by sunny** [sunny/pw-conference-generator#27]
https://dev.sunfox.org/paris-web/?c=Q0dJwqA6IHF1ZSBmYWlyZSBlbiB0YW50IHF1ZSB1bmUgaGFja2V1c2UgcnVzc2UgZHUgbGVzIG5vdXZlbGxlcyByw6lnbGVtZW50YXRpb25zIGlzb2zDqWVzwqA%2F

**Comment by joachimesque** [comment]
« Apple : que faire en tant que une ado du Photoshop ? »
